-- SQL Script to create the 'volunteer_tasks' table in Supabase
-- Run this in your Supabase Dashboard SQL Editor (https://supabase.com)

CREATE TABLE IF NOT EXISTS public.volunteer_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  volunteer_id BIGINT REFERENCES public.volunteer_applications(id) ON DELETE CASCADE,
  task_title TEXT NOT NULL,
  task_description TEXT,
  task_date TEXT NOT NULL,
  task_time TEXT NOT NULL,
  status TEXT DEFAULT 'Pending',
  assigned_money NUMERIC DEFAULT 0,
  money_received NUMERIC DEFAULT 0,
  money_spent NUMERIC DEFAULT 0,
  proof_media TEXT,
  feedback TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.volunteer_tasks ENABLE ROW LEVEL SECURITY;

-- Create security policies
-- Allow public read access (for fetching tasks via the public client)
CREATE POLICY "Allow public read access" ON public.volunteer_tasks
  FOR SELECT USING (true);

-- Allow service role/admin write access (for inserts, updates, and deletes)
CREATE POLICY "Allow service role write access" ON public.volunteer_tasks
  USING (true)
  WITH CHECK (true);
