-- SQL Script to create the 'contact_info' table in Supabase
-- Run this in your Supabase Dashboard SQL Editor (https://supabase.com)

-- 1. Create the contact_info table
CREATE TABLE IF NOT EXISTS public.contact_info (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  value TEXT NOT NULL,
  type TEXT NOT NULL,
  icon TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.contact_info ENABLE ROW LEVEL SECURITY;

-- 3. Create security policies
-- Allow public select access
DROP POLICY IF EXISTS "Allow public read access" ON public.contact_info;
CREATE POLICY "Allow public read access" ON public.contact_info
  FOR SELECT USING (true);

-- Allow administrative service role full read/write access
DROP POLICY IF EXISTS "Allow service role write access" ON public.contact_info;
CREATE POLICY "Allow service role write access" ON public.contact_info
  USING (true)
  WITH CHECK (true);

-- 4. Seed default contact cards
INSERT INTO public.contact_info (id, title, value, type, icon) VALUES 
(1, 'Registered Address', 'Kanha Foundation Office,\nRanchi, Jharkhand, 834001, India', 'address', 'map-pin'),
(2, 'Email Inquiry', 'support@kanhafoundation.org', 'email', 'mail'),
(3, 'WhatsApp Support', '+91 74881 64529', 'whatsapp', 'whatsapp')
ON CONFLICT (id) DO UPDATE 
SET title = EXCLUDED.title, value = EXCLUDED.value, type = EXCLUDED.type, icon = EXCLUDED.icon;
