-- SQL Script to create the 'categories' table in Supabase
-- Run this in your Supabase Dashboard SQL Editor (https://supabase.com)

-- 1. Create the categories table
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;

-- 3. Create security policies (optional but recommended)
-- Allow anyone to read categories
CREATE POLICY "Allow public read access" ON public.categories
  FOR SELECT USING (true);

-- Allow authenticated service role/admin to insert/update/delete
CREATE POLICY "Allow service role write access" ON public.categories
  USING (true)
  WITH CHECK (true);
