-- SQL Script to create the 'star_volunteers' table in Supabase
-- Run this in your Supabase Dashboard SQL Editor (https://supabase.com)

CREATE TABLE IF NOT EXISTS public.star_volunteers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  volunteer_id BIGINT,
  name TEXT NOT NULL,
  gender TEXT,
  email TEXT,
  phone TEXT,
  profile_photo TEXT,
  grade TEXT NOT NULL,
  reason TEXT NOT NULL,
  week_label TEXT DEFAULT 'This Week',
  tasks_completed INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.star_volunteers ENABLE ROW LEVEL SECURITY;

-- Create security policies
-- Allow anyone to read
CREATE POLICY "Allow public read access" ON public.star_volunteers
  FOR SELECT USING (true);

-- Allow authenticated service role/admin to insert/update/delete
CREATE POLICY "Allow service role write access" ON public.star_volunteers
  USING (true)
  WITH CHECK (true);
