-- SQL Script to create the 'beneficiaries' table in Supabase
-- Run this in your Supabase Dashboard SQL Editor (https://supabase.com)

CREATE TABLE IF NOT EXISTS public.beneficiaries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  father_name TEXT NOT NULL,
  mother_name TEXT NOT NULL,
  address TEXT NOT NULL,
  father_aadhar_number TEXT,
  father_aadhar_upload_url TEXT,
  mother_aadhar_number TEXT,
  mother_aadhar_upload_url TEXT,
  children JSONB DEFAULT '[]'::jsonb, -- Array of child objects: { name: string, dob: string, aadhar_number?: string, aadhar_upload_url?: string }
  causes_donated JSONB DEFAULT '[]'::jsonb, -- Array of strings (cause names or IDs)
  donation_pic_url TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.beneficiaries ENABLE ROW LEVEL SECURITY;

-- Create security policies
-- Allow anyone to read
CREATE POLICY "Allow public read access" ON public.beneficiaries
  FOR SELECT USING (true);

-- Allow authenticated service role/admin to insert/update/delete
CREATE POLICY "Allow service role write access" ON public.beneficiaries
  USING (true)
  WITH CHECK (true);
